### ISSUE TITLE
需求：获取级联选择器中的label值

### ISSUE THREAD

**Issue by DuJunlong321** [heyu3913/el-cascader-onlylast-mutiple#1]
需求：获取级联选择器中的label值
查阅了资料，普通的el-cascader都是像这样实现，目前你的组件会报错。
<img width="547" alt="b0300a1ddb46e1c3cd7b2cc521f991b" src="https://github.com/user-attachments/assets/31159506-28c4-45a3-9e66-10c102d3aca0">

希望能添加该功能。

**Comment by heyu3913** [comment]
1.0.3版本已添加该功能
